# Generated by Django 2.0.4 on 2018-04-25 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0002_auto_20180425_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='album',
        ),
    ]
