# Generated by Django 2.0.4 on 2018-04-27 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0003_auto_20180427_0242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='photos',
        ),
        migrations.AddField(
            model_name='photo',
            name='albums',
            field=models.ManyToManyField(to='imager_images.Album'),
        ),
    ]
