# Generated by Django 2.0.4 on 2018-04-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0004_auto_20180427_0320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='albums',
        ),
        migrations.AddField(
            model_name='album',
            name='photos',
            field=models.ManyToManyField(related_name='album', to='imager_images.Photo'),
        ),
    ]
